### ISSUE TITLE
Twitter creds committed to repo?

### ISSUE THREAD

**Issue by crookedneighbor** [sonnylazuardi/require-tweet#1]
I assume you intended to publish your creds to Github and npm? https://github.com/sonnylazuardi/require-tweet/blob/4fc700a2d5efc714b302d6f81a0cfbb4141c666f/index.js#L7-L12

Seems like those would be better served as environmental variables that a user would supply themselves.

**Comment by sonnylazuardi** [comment]
yeah, I intended yo publish my creds for simplicity (users don't need to register a twitter app and copy pasting their creds). But for scalability I think this is bad beause it will definitely cause a rate limit api request. So I will change it soon so that we can use env variables to set the creds. Thanks for your input @crookedneighbor
